//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrillaSegFact.WP_Creado {
    
    
    public partial class WP_CreadoUserControl {
        
        /// <summary>
        /// ltTablaCreadoPorMiCO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltTablaCreadoPorMiCO;
        
        /// <summary>
        /// ltTablaCreadoPorMiSO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltTablaCreadoPorMiSO;
    }
}
